version: "3.8"

networks:
  swarm_bank_net:
    external: true

services:
  bank:
    image: bank:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - swarm_bank_net
    environment:
      - MIX_ENV=prod